# Site settings
title: Vega Lau的个人博客
email: VegaLau@qq.com
description: > #Vega Lau的个人博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yujie2020.github.io" # the base hostname & protocol for your site

# Paginate（分页）
#gems: [jekyll-paginate]
# 分页时每页博文数量
#paginate: 10
#paginate_path: "page:num"


# Build settings
# 语法高亮
#highlighter: pygments
# markdown解释器
#markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#relative_permalinks: true
#博文的链接样式
permalink: /:year-:month-:day-:title.html

favicon: /assets/image/favicon.ico

# 博客作者相关
author:
  name: Vega Lau
  email: VegaLau@qq.com
  link: https://yujie2020.github.io
  weibo: http://www.weibo.com
  weibo_username: null
  github: https://github.com/YuJie2020
  github_username: YuJie


locals:
  tags: 标签
  about: 关于
  active: 技术
subscribe_rss: /pages/atom.xml

# 头像
avatar: /assets/image/avatar.png
# avatar: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/image/favicon.ico
# 网站CSS路径
css: /assets/css/
# css: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/css/
# 网站JS路径
js: /assets/js/
# js: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/js/
# 网站图片路径
image: /assets/image/
# image: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/image/

# disqus 设置
disqus:
  shortname: VegaLau
